# Generated by Django 2.0.6 on 2018-06-26 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('number_of_visits', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_state', models.BooleanField()),
                ('time_of_event', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time_of_event'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('door_eid', models.CharField(max_length=100, unique=True)),
                ('threshold', models.IntegerField()),
                ('visits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.Room'),
        ),
        migrations.AddField(
            model_name='cleaninghistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.Room'),
        ),
        migrations.AddField(
            model_name='cleaninghistory',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
