# Generated by Django 2.0.6 on 2018-06-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Unknown room', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
