# Generated by Django 2.1.5 on 2019-01-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0002_auto_20180627_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='notification_phone_number',
            field=models.CharField(default='12312123', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
