# Generated by Django 2.1.5 on 2019-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0003_auto_20190112_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninghistory',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
